#
###################################
# Site wide configuration
####################################
#
title: Dr. Woo의 블로그
email: zorba10x@gmail.com
description: Everything I like
url: https://kjeiwoo.github.io/
# the base hostname & protocol for your site


#
###################################
# Jekyll configuration
####################################
#
timezone:          Asia/Seoul
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Dr. WOO (우 경 제)
  avatar: logo.png
  job: "Awaken Daydreamer"
  bio: "연세본우정형외과 원장 / 신기한 것을 공부하기 좋아하는 / 귀여운 세 아이의 아빠입니다"
  email: zorba10x@gmail.com
  disqus-shortname: kjwoo
  twitter: spikyedge #username
  facebook: kyungjei.woo #username
  google:
    plus: #username
    analytics: UA-62251910-2
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: kjeiwoo #username
  stackoverflow: 7252095/daniel-woo #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: kyungjei-woo-a34489b2 #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username
